import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Search, FileSearch, Map, Sparkles, ArrowRight, History } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { supabase } from "@/lib/supabase"
import { formatDistanceToNow } from "date-fns"

const features = [
    {
        title: "Deep Research",
        description: "Synthesize academic papers and career data with high accuracy.",
        icon: Search,
        href: "/deep-research",
        color: "bg-blue-500/10 text-blue-600",
    },
    {
        title: "PaperBreaker",
        description: "Upload PDFs to get simplified summaries and jargon-free explanations.",
        icon: FileSearch,
        href: "/paperbreaker",
        color: "bg-purple-500/10 text-purple-600",
    },
    {
        title: "PathFinder AI",
        icon: Map,
        description: "Generate a personalized roadmap for your major or career goals.",
        href: "/pathfinder",
        color: "bg-emerald-500/10 text-emerald-600",
    },
]

export default async function DashboardPage() {
    // Fetch recent activity from Supabase
    const { data: history } = await supabase
        .from('research_history')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(5)

    return (
        <div className="space-y-8">
            <div>
                <h1 className="text-3xl font-bold tracking-tight text-foreground">Welcome to BrightBridge</h1>
                <p className="text-muted-foreground mt-2">
                    Your AI-powered toolkit for academic and career excellence.
                </p>
            </div>

            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                {features.map((feature) => (
                    <Card key={feature.title} className="group relative overflow-hidden transition-all hover:shadow-lg">
                        <CardHeader>
                            <div className={`mb-4 flex h-10 w-10 items-center justify-center rounded-lg ${feature.color}`}>
                                <feature.icon className="h-5 w-5" />
                            </div>
                            <CardTitle className="group-hover:text-[#1E3A8A] transition-colors">
                                {feature.title}
                            </CardTitle>
                            <CardDescription>{feature.description}</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Button asChild variant="ghost" className="group/btn w-full justify-between hover:bg-[#1E3A8A] hover:text-white">
                                <Link href={feature.href}>
                                    Get Started
                                    <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover/btn:translate-x-1" />
                                </Link>
                            </Button>
                        </CardContent>
                    </Card>
                ))}
            </div>

            <Card className="shadow-sm border-border/50">
                <CardHeader>
                    <div className="flex items-center gap-2">
                        <History className="h-5 w-5 text-[#1E3A8A]" />
                        <CardTitle>Recent Activity</CardTitle>
                    </div>
                    <CardDescription>
                        {history && history.length > 0
                            ? "Your latest research and insights generated by AI."
                            : "You haven't performed any research yet. Start your first session above!"}
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {history && history.length > 0 ? (
                        <div className="space-y-4">
                            {history.map((item: any) => (
                                <div key={item.id} className="flex items-start gap-4 p-3 rounded-lg hover:bg-muted/50 transition-colors border border-transparent hover:border-border/50">
                                    <div className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${item.type === 'deep-research' ? 'bg-blue-500/10 text-blue-600' :
                                        item.type === 'paperbreaker' ? 'bg-purple-500/10 text-purple-600' :
                                            'bg-emerald-500/10 text-emerald-600'
                                        }`}>
                                        {item.type === 'deep-research' ? <Search className="h-4 w-4" /> :
                                            item.type === 'paperbreaker' ? <FileSearch className="h-4 w-4" /> :
                                                <Map className="h-4 w-4" />}
                                    </div>
                                    <div className="flex-1 space-y-1">
                                        <p className="text-sm font-medium leading-none capitalize">
                                            {item.type.replace('-', ' ')}
                                        </p>
                                        <p className="text-sm text-muted-foreground line-clamp-1">
                                            {item.query}
                                        </p>
                                        <p className="text-xs text-muted-foreground">
                                            {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                                        </p>
                                    </div>
                                    <Button variant="ghost" size="sm" asChild>
                                        <Link href={`/${item.type}`}>View</Link>
                                    </Button>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center py-8 text-center border-2 border-dashed rounded-xl border-border/50">
                            <Sparkles className="h-10 w-10 text-muted-foreground/30 mb-3" />
                            <p className="text-sm text-muted-foreground">No activity found yet.</p>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    )
}
